import type { PermissionAction } from "@/shared/permissions/types"

export const PERMISSION_ACTION_CATALOG: Record<PermissionAction, string> = {
  "root.college.create": "在根级新增学校",
  "college.department.create": "在学校下新增院系",
  "department.major.create": "在院系下新增专业",
  "major.course.create": "在专业下新增课程",
  "college.member.create": "学校成员新增",
  "college.member.edit": "学校成员编辑",
  "college.member.delete": "学校成员删除",
  "college.member.toggle": "学校成员启用/禁用",
  "college.member.resetPassword": "学校成员重置密码",
  "department.member.create": "院系成员新增",
  "department.member.edit": "院系成员编辑",
  "department.member.delete": "院系成员删除",
  "department.member.toggle": "院系成员启用/禁用",
  "department.member.resetPassword": "院系成员重置密码",
  "major.member.create": "专业成员新增",
  "major.member.edit": "专业成员编辑",
  "major.member.delete": "专业成员删除",
  "major.member.toggle": "专业成员启用/禁用",
  "major.member.resetPassword": "专业成员重置密码",
  "course.member.create": "课程成员新增",
  "course.member.edit": "课程成员编辑",
  "course.member.delete": "课程成员删除",
  "course.member.toggle": "课程成员启用/禁用",
  "course.member.resetPassword": "课程成员重置密码",
  "college.teachingTask.create": "学校教学任务新增",
  "college.teachingTask.manage": "学校教学任务管理",
}
