import type { PermissionMatrix } from "@/shared/permissions/types"

export const PERMISSION_MATRIX: PermissionMatrix = {
  1: [
    "root.college.create",
    "college.department.create",
    "department.major.create",
    "major.detail.edit",
    "major.course.create",
    "course.detail.edit",
    "college.member.create",
    "college.member.edit",
    "college.member.delete",
    "college.member.toggle",
    "college.member.resetPassword",
    "department.member.create",
    "department.member.edit",
    "department.member.delete",
    "department.member.toggle",
    "department.member.resetPassword",
    "college.qa.create",
    "college.qa.manage",
  ],
  88: [
    "root.college.create",
    "college.department.create",
    "department.major.create",
    "major.detail.edit",
    "major.course.create",
    "course.detail.edit",
    "college.member.create",
    "college.member.edit",
    "college.member.delete",
    "college.member.toggle",
    "college.member.resetPassword",
    "department.member.create",
    "department.member.edit",
    "department.member.delete",
    "department.member.toggle",
    "department.member.resetPassword",
    "college.qa.create",
    "college.qa.manage",
  ],
  1001: [
    "department.major.create",
    "major.detail.edit",
    "major.course.create",
    "course.detail.edit",
    "department.member.create",
    "department.member.edit",
    "department.member.delete",
    "department.member.toggle",
    "department.member.resetPassword",
  ],
  1031: [
    "major.course.create",
    "college.qa.manage",
    "course.detail.edit",
  ],
  1039: [
    "major.course.create",
    "college.qa.create",
    "college.qa.manage",
    "course.detail.edit",
  ],
  1901: [
    "department.major.create",
    "major.course.create",
    "course.detail.edit",
  ],
  2001: [
    "department.major.create",
    "major.detail.edit",
    "major.course.create",
    "course.detail.edit",
  ],
  3001: [
    "course.detail.edit",
  ],
}
