import type { PermissionMatrix } from "@/shared/permissions/types"

export const PERMISSION_MATRIX: PermissionMatrix = {
  1: [
    "root.college.create",
    "college.department.create",
    "department.major.create",
    "major.course.create",
    "college.member.create",
    "college.member.edit",
    "college.member.delete",
    "college.member.toggle",
    "college.member.resetPassword",
    "department.member.create",
    "department.member.edit",
    "department.member.delete",
    "department.member.toggle",
    "department.member.resetPassword",
    "major.member.create",
    "major.member.edit",
    "major.member.delete",
    "major.member.toggle",
    "major.member.resetPassword",
    "course.member.create",
    "course.member.edit",
    "course.member.delete",
    "course.member.toggle",
    "course.member.resetPassword",
    "college.teachingTask.create",
    "college.teachingTask.manage",
  ],
  88: [
    "root.college.create",
    "college.department.create",
    "department.major.create",
    "major.course.create",
    "college.member.create",
    "college.member.edit",
    "college.member.delete",
    "college.member.toggle",
    "college.member.resetPassword",
    "department.member.create",
    "department.member.edit",
    "department.member.delete",
    "department.member.toggle",
    "department.member.resetPassword",
    "major.member.create",
    "major.member.edit",
    "major.member.delete",
    "major.member.toggle",
    "major.member.resetPassword",
    "course.member.create",
    "course.member.edit",
    "course.member.delete",
    "course.member.toggle",
    "course.member.resetPassword",
    "college.teachingTask.create",
    "college.teachingTask.manage",
  ],
  1001: [
    "department.major.create",
    "major.course.create",
    "department.member.create",
    "department.member.edit",
    "department.member.delete",
    "department.member.toggle",
    "department.member.resetPassword",
    "major.member.create",
    "major.member.edit",
    "major.member.delete",
    "major.member.toggle",
    "major.member.resetPassword",
    "course.member.create",
    "course.member.edit",
    "course.member.delete",
    "course.member.toggle",
    "course.member.resetPassword",
  ],
  1031: [
    "college.teachingTask.manage",
  ],
  1039: [
    "college.teachingTask.create",
    "college.teachingTask.manage",
  ],
  1901: [],
  2001: [
    "major.course.create",
    "major.member.create",
    "major.member.edit",
    "major.member.delete",
    "major.member.toggle",
    "major.member.resetPassword",
    "course.member.create",
    "course.member.edit",
    "course.member.delete",
    "course.member.toggle",
    "course.member.resetPassword",
  ],
  3001: [
    "course.member.create",
    "course.member.edit",
    "course.member.delete",
    "course.member.toggle",
    "course.member.resetPassword",
  ],
}
